
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18

  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - yarn install
      - echo Build completed on `date`
      - yarn build
      - ls -la
      - cd build && ls -la && cd ..
  post_build:
    commands:
      - echo copy files on s3 on `date`
      - aws s3 cp build/ s3://soban-static/ --recursive
      
