
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18

  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - yarn add
  post_build:
    commands:
      - echo Build completed on `date`
      - yarn run build
      
artifacts:
  files:
    - dist/*
