name: Upload to S3
on: 
  push:
    branches: [ master ]
#on: [pull_request]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      # Runs a single command using the runners shell
      - name: Install Node js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      - uses: borales/actions-yarn@v2.0.0
        with:
            cmd: install # will run `yarn install` command  
      - name: yarn create react app
        run: yarn build && ls -la
      
